            <div class="BodyTitle">
                <a href="/index.html">ficus.cafe</a>
            </div>
            <nav class="MainNav">
                <p>
                    <a href="/index.html">Latest</a><a
                        href="/mods.html">Mods</a><a
                        href="/writings.html">Writings</a><a
                        href="/catshrine.html">Shrine</a><a
                        href="/about.html">About</a>
                </p>
            </nav>
            <hr id="MainNavLine" />
