            <div class="BodyTitle">
                <a href="/index.html">ficus&#129716cafe</a>
            </div>
            <nav class="MainNav">
                <p>
                    <a href="/index.html">&#128226<br />Latest</a><a
                        href="/mods.html">&#129520<br />Mods</a><a
                        href="/writings.html">&#128221<br />Writings</a><a
                        href="/catshrine.html">&#x1F408<br />猫寺</a><a
                        href="/about.html">&#8265&#65039<br />About</a>
                </p>
            </nav>
            <hr id="MainNavLine" />
